name: Weather Prediction Workflow

on:
  push:
    paths:
      - "data/weather_data.csv"  # Run the workflow when this file changes
  workflow_dispatch:  # Allow manual trigger from GitHub Actions tab

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn joblib matplotlib

    - name: Run preprocessing script
      run: |
        python scripts/load_and_preprocess.py

    - name: Run feature engineering script
      run: |
        python scripts/feature_engineering.py

    - name: Train model
      run: |
        python scripts/model_training.py

    - name: Save trained model
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-github-username"
        git add weather_model.pkl
        git commit -m "Update trained weather model"
        git push
